name: federatorai-demo
version: 0.1.1
description: Federator.ai Demo
  Federator.ai is the brain of resource orchestration for Kubernetes. It
  is a prediction engine that foresees future resource usage of your Kubernetes cluster
  from the cloud layer down to the pod level. We use machine learning technology to
  provide intelligence that enables dynamic scaling and scheduling of your containers
  - effectively making us the brain of Kubernetes resource orchestration. By
  providing full foresight of resource availability, demand, health, impact and SLA,
  we enable cloud strategies that involve changing provisioned resources in real time.
home: https://www.prophetstor.com
icon: https://raw.githubusercontent.com/cheesiong-lee/federatorai-operator/master/helm/logo.png
keywords:
- AI
- AIOps
- Kubernetes
maintainers:
- email: support@prophetstor.com
  name: ProphetStor Data Services, Inc.
sources:
- https://github.com/containers-ai/federatorai-demo
